/* This file is auto-generated by @proto.ui/cli. */
/* Do not edit by hand. */

export { ShadcnButton as ReactShadcnButton } from './react';
export { ShadcnDialogRoot as ReactShadcnDialogRoot } from './react';
export { ShadcnDialogTrigger as ReactShadcnDialogTrigger } from './react';
export { ShadcnDialogMask as ReactShadcnDialogMask } from './react';
export { ShadcnDialogContent as ReactShadcnDialogContent } from './react';
export { ShadcnDialogTitle as ReactShadcnDialogTitle } from './react';
export { ShadcnDialogDescription as ReactShadcnDialogDescription } from './react';
export { ShadcnDialogClose as ReactShadcnDialogClose } from './react';
export { ShadcnSwitchRoot as ReactShadcnSwitchRoot } from './react';
export { ShadcnSwitchThumb as ReactShadcnSwitchThumb } from './react';
export { ShadcnTabsRoot as ReactShadcnTabsRoot } from './react';
export { ShadcnTabsList as ReactShadcnTabsList } from './react';
export { ShadcnTabsTrigger as ReactShadcnTabsTrigger } from './react';
export { ShadcnTabsContent as ReactShadcnTabsContent } from './react';
