/* This file is auto-generated by @proto.ui/cli. */
/* Do not edit by hand. */

import { createReactAdapter } from '@proto.ui/adapter-react';
import * as React from 'react';
import { shadcnButton } from '@proto.ui/prototypes-shadcn/button';

const adapt = createReactAdapter(React);

export const ShadcnButton = adapt(shadcnButton);
