/* This file is auto-generated by @proto.ui/cli. */
/* Do not edit by hand. */

import { createReactAdapter } from '@proto.ui/adapter-react';
import * as React from 'react';
import { shadcnButton } from '@proto.ui/prototypes-shadcn/button';
import { shadcnDialogClose, shadcnDialogCloseIcon, shadcnDialogContent, shadcnDialogDescription, shadcnDialogFooter, shadcnDialogHeader, shadcnDialogMask, shadcnDialogRoot, shadcnDialogTitle, shadcnDialogTrigger } from '@proto.ui/prototypes-shadcn/dialog';
import { shadcnSwitchRoot, shadcnSwitchThumb } from '@proto.ui/prototypes-shadcn/switch';

const adapt = createReactAdapter(React);

export const ShadcnButton = adapt(shadcnButton);

export const ShadcnDialogRoot = adapt(shadcnDialogRoot);
export const ShadcnDialogTrigger = adapt(shadcnDialogTrigger);
export const ShadcnDialogMask = adapt(shadcnDialogMask);
export const ShadcnDialogContentRaw = adapt(shadcnDialogContent);
export const ShadcnDialogTitle = adapt(shadcnDialogTitle);
export const ShadcnDialogDescription = adapt(shadcnDialogDescription);
export const ShadcnDialogClose = adapt(shadcnDialogClose);
export const ShadcnDialogCloseIcon = adapt(shadcnDialogCloseIcon);
export const ShadcnDialogHeader = adapt(shadcnDialogHeader);
export const ShadcnDialogFooter = adapt(shadcnDialogFooter);
export type ShadcnDialogContentProps = Omit<React.ComponentProps<typeof ShadcnDialogContentRaw>, 'children'> & {
  children?: React.ReactNode;
  close?: React.ReactElement<React.ComponentProps<typeof ShadcnDialogCloseIcon>, typeof ShadcnDialogCloseIcon> | null;
};
export const ShadcnDialogContent = React.forwardRef<React.ComponentRef<typeof ShadcnDialogContentRaw>, ShadcnDialogContentProps>(
  ({ close, children, ...props }, ref) => {
    const childList = React.Children.toArray(children);
    const hasDirectDefaultPart = childList.some(
      (child) => React.isValidElement(child) && child.type === ShadcnDialogCloseIcon
    );
    const resolvedDefaultPart =
      close === null || hasDirectDefaultPart
        ? null
        : close ?? React.createElement(ShadcnDialogCloseIcon);
    const rootProps = ref == null ? props : { ...props, ref };
    return React.createElement(ShadcnDialogContentRaw, rootProps, children, resolvedDefaultPart);
  }
);
ShadcnDialogContent.displayName = 'ShadcnDialogContent';

export const ShadcnSwitchRoot = adapt(shadcnSwitchRoot);
export const ShadcnSwitchThumb = adapt(shadcnSwitchThumb);
export type ShadcnSwitchProps = Omit<React.ComponentProps<typeof ShadcnSwitchRoot>, 'children'> & {
  children?: React.ReactNode;
  thumb?: React.ReactElement<React.ComponentProps<typeof ShadcnSwitchThumb>, typeof ShadcnSwitchThumb> | null;
};
export const ShadcnSwitch = React.forwardRef<React.ComponentRef<typeof ShadcnSwitchRoot>, ShadcnSwitchProps>(
  ({ thumb, children, ...props }, ref) => {
    const childList = React.Children.toArray(children);
    const hasDirectDefaultPart = childList.some(
      (child) => React.isValidElement(child) && child.type === ShadcnSwitchThumb
    );
    const resolvedDefaultPart =
      thumb === null || hasDirectDefaultPart
        ? null
        : thumb ?? React.createElement(ShadcnSwitchThumb);
    const rootProps = ref == null ? props : { ...props, ref };
    return React.createElement(ShadcnSwitchRoot, rootProps, children, resolvedDefaultPart);
  }
);
ShadcnSwitch.displayName = 'ShadcnSwitch';
