/* This file is auto-generated by @proto.ui/cli. */
/* Do not edit by hand. */

import { createReactAdapter } from '@proto.ui/adapter-react';
import * as React from 'react';
import { shadcnButton } from '@proto.ui/prototypes-shadcn/button';
import { shadcnDialogClose, shadcnDialogContent, shadcnDialogDescription, shadcnDialogMask, shadcnDialogRoot, shadcnDialogTitle, shadcnDialogTrigger } from '@proto.ui/prototypes-shadcn/dialog';
import { shadcnSwitchRoot, shadcnSwitchThumb } from '@proto.ui/prototypes-shadcn/switch';
import { shadcnTabsContent, shadcnTabsList, shadcnTabsRoot, shadcnTabsTrigger } from '@proto.ui/prototypes-shadcn/tabs';

const adapt = createReactAdapter(React);

export const ShadcnButton = adapt(shadcnButton);

export const ShadcnDialogRoot = adapt(shadcnDialogRoot);
export const ShadcnDialogTrigger = adapt(shadcnDialogTrigger);
export const ShadcnDialogMask = adapt(shadcnDialogMask);
export const ShadcnDialogContent = adapt(shadcnDialogContent);
export const ShadcnDialogTitle = adapt(shadcnDialogTitle);
export const ShadcnDialogDescription = adapt(shadcnDialogDescription);
export const ShadcnDialogClose = adapt(shadcnDialogClose);

export const ShadcnSwitchRoot = adapt(shadcnSwitchRoot);
export const ShadcnSwitchThumb = adapt(shadcnSwitchThumb);

export const ShadcnTabsRoot = adapt(shadcnTabsRoot);
export const ShadcnTabsList = adapt(shadcnTabsList);
export const ShadcnTabsTrigger = adapt(shadcnTabsTrigger);
export const ShadcnTabsContent = adapt(shadcnTabsContent);
